### ISSUE TITLE
Ligature suppression suggestion: halfling

### ISSUE THREAD

**Issue by habere-et-dispertire** [micoloretan/selnolig#14]
Rereading *The Lord of the Rings*, I noticed the lack of ligature suppression on the word "halfling". If this is in scope, please consider adding suppression for this word in English as I think the morpheme boundary is half-ling, not hal-fling.

Thank you for respecting morpheme boundaries!
:)

**Comment by micoloretan** [comment]
An excellent sugggestion! At the moment, selnolig is set to capture the cases 'halfline', 'halflfe', and 'halflives' (if the 'english' language option is set), but not yet 'halfling'. I will be happy to modify the applicable rule -- the new rule will likely be \nolig{[Hh]alfli}{half|li} -- the next time I update selnolig, to capture both 'halfling' and 'Halfling' as well.

**Comment by habere-et-dispertire** [comment]
Thank you Mico!
