### ISSUE TITLE
Ligature suppression suggestion: selfie

### ISSUE THREAD

**Issue by habere-et-dispertire** [micoloretan/selnolig#15]
Bonjour !

My dictionary lists the origin of selfie as:

Early 21st century: from self + -ie.

So I think this is a candidate for suppression back to self-ie.

Merci !

**Comment by micoloretan** [comment]
Many thanks for this suggestion. I will add the rule \nolig{[Ss]elfie}{self|ie} to the set of ligature suppression rules enabled by the package's 'broadf' option.

**Comment by habere-et-dispertire** [comment]
Thank you Mico. Glad to be of help. These things are fun and hard to spot!
