### ISSUE TITLE
`` and '' are having too much space when cfr-lm is used

### ISSUE THREAD

**Issue by koppor** [micoloretan/selnolig#8]
![grafik](https://user-images.githubusercontent.com/1366654/37178584-2c778a56-2323-11e8-817f-63ca26625d84.png)

## Minimal example

```
\documentclass{article}
\usepackage{fontspec}
\usepackage{selnolig}
\usepackage{csquotes}
\usepackage{cfr-lm}
\begin{document}
``this'' versus \enquote{that}.
\end{document}
```

## lq and rq also do not work

![grafik](https://user-images.githubusercontent.com/1366654/37178770-ca16d4e2-2323-11e8-9abf-494275b91fbb.png)

(Source: https://tex.stackexchange.com/a/36845/9075)

```
\documentclass{article}
\usepackage{fontspec}
\usepackage{selnolig}
\usepackage{csquotes}
\usepackage{cfr-lm}
\begin{document}
``plain'' versus \lq\lq lqrq\rq\rq{} versus \enquote{enquote}.
\end{document}
```

**Comment by micoloretan** [comment]
A comment up front: I only ever intended/anticipated that selnolig would be used with OpenType fonts. For sure, if one replaces '\usepackage{cfr-lm}' with '\setmainfont{Latin Modern Roman}[Numbers=OldStyle]', there's no problem -- at least not with the opening quotes...

I'm afraid I don't know nearly enough about the cfr-lm package to even hazard a guess as to what might be going on. Have you contacted Clea about this?

Regards, Mico

**Comment by koppor** [comment]
Thank you for the quick response. I think, this is worth an answer at https://tex.stackexchange.com/q/419218/9075, isn't it? I am a newbie in lualatex/selnolig and I am unsure whether I really need `\setmainfont{Latin Modern Roman}`. As far as I understand, it switches to the new font (variant) and lualatex uses the "old" one ("Computer Modern Roman"?) as default?

You now, the discussion cmodern vs. lmodern vs. cfr-lm. 😇

**Comment by koppor** [comment]
For the googlers landing here: Related issues

- https://tex.stackexchange.com/questions/419288/microtypecontext-with-lualatex
- Release of [luafontenc](https://github.com/michal-h21/luafontenc) to enable [newtxtt](https://ctan.org/pkg/newtxtt) to be used in lualatex. See [comment](https://tex.stackexchange.com/questions/243482/switching-to-lualatex-how-to-translate-font-setups/243486?noredirect=1#comment1049559_243486) to question [Switching to lualatex: How to translate font setups?](https://tex.stackexchange.com/q/243482/9075).
